### PR TITLE
Wtf

### PR DESCRIPTION
**Pull request by jordanwheeler**

### CODE REVIEW

**Comment by jordanwheeler** [comment]
ping @Shopify/POS this PR touches POS-related tests!

**Comment by jordanwheeler** [comment]
ping @Shopify/webscale this PR touches web external tests!

**Review by RadaofTheLight — APPROVED** [review]
b3daaaa1e8dabfeeec74d782d531dc85238ce52c

**Comment by RadaofTheLight** [comment]
Pull requests

**Pull request merged**
